website/account/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete

app_name = 'account'

urlpatterns = [
    # Format of URL
    # url(r'^name_of_url/$', file that show view, name='name of this url'),

    # URL to register page
    url(r'^register/$', views.register, name='register'),

    # URL to login page
    url(r'^$', login, {'template_name': 'account/index.html'}, name='index'),

    # URL to profile page
    url(r'^profile/$', views.profile, name='profile'),

    # URL to edit profile page
    url(r'^profile/edit/$', views.edit_profile, name='edit_profile'),

    # URL to logout page
    url(r'^logout/$', views.logout_view, name='logout_view'),

    # URL to password change page
    url(r'^profile/password/$', views.change_password, name='change_password'),

    # URL to delete account page
    url(r'^delete-account/$', views.del_user, name='del_user'),

    # URL to reset password page
    url(r'^reset-password/$', password_reset, {'template_name': 'account/reset_password.html', 'post_reset_redirect': 'account:password_reset_done', 'email_template_name': 'account/reset_password_email.html'}, name='reset_password'),

    # URL to reset password done page
    url(r'^reset-password/done/$', password_reset_done, {'template_name': 'account/reset_password_done.html'}, name='password_reset_done'),

    # URL to reset password confirm page
    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm, {'template_name': 'account/reset_password_confirm.html', 'post_reset_redirect': 'account:password_reset_complete'}, name='password_reset_confirm'),

    # URL to reset password complete page
    url(r'^reset-password/complete/$', password_reset_complete,{'template_name': 'account/reset_password_complete.html'}, name='password_reset_complete'),

]
##python -m smtpd -n -c DebuggingServer localhost:1025

website/catalog/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'catalog'
# r'^(?P<selection>[\w-]+)/$' is a *regular expression* looking for string variables
# The ones with [0-9] are integerss
urlpatterns = [

    url(r'^catalog/', include([
        # INDEX IS ALWAYS THE MAIN/HOME PAGE FOR AN APP
        url(r'^$', views.index, name='index'),

        # MENS/WOMENS CATEGORY SELECTION PAGE
        url(r'^(?P<selection>[\w-]+)/$', views.mw, name='mw'),

        # MENS/WOMENS CATEGORY SELECTION PAGE
        url(r'^(?P<selection>[\w-]+)/(?P<order>[\w-]+)/(?P<order_type>[\w-]+)/$', views.mw, name='mw_with_sort'),

        # CATEGORY PAGE DISPLAYING PRODUCTS
        url(r'^(?P<selection>[\w-]+)/(?P<category>[ \w-]+)/$', views.products_list, name='products_list'),

        # CATEGORY PAGE DISPLAYING PRODUCTS WITH SORT
        url(r'^(?P<selection>[\w-]+)/(?P<category>[ \w-]+)/(?P<order>[\w-]+)/(?P<order_type>[\w-]+)/$', views.products_list, name='products_list_with_sort'),

        ])),

    # PRODUCT PAGE DISPLAYING PRODUCT INFO
    url(r'^(?P<p_id>[0-9]+)/$', views.product, name='prod'),

    # PRODUCT PAGE DISPLAYING PRODUCT INFO
    url(r'^(?P<p_id>[0-9]+)/(?P<thumbnail_image>[ \d-]+)/$', views.product, name='prod'),

    # ITEM ADDED TO CART CONFIRMATION PAGE
    url(r'^cart/cart_confirmation/(?P<p_id>[0-9]+)/$', views.cart_confirmation, name='cart_confirmation'),

    # CART PAGE
    url(r'^cart/$', views.get_cart, name='get_cart'),

    # ABOUT US
    url(r'^about/', views.about, name='about'),

    # HOME PAGE
    url(r'^$', views.index, name='index'),

]

website/search/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'search'

urlpatterns = [
    # DEFAULT SEARCH RESULTS PAGE
    url(r'^$', views.search, name='search'),
    # FILTERED SEARCH PAGE
    url(r'^sex_(?P<sex>[\w-]+)_cat_(?P<category>[ \w-]+)_size_(?P<size>[\w-]+)_order_(?P<order>[\w-]+)_(?P<order_type>[\w-]+)/$', views.search, name='search'),
]

website/website/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # HOME PAGE/CATALOG APP
    url(r'^', include('catalog.urls')),
    # SEARCH PAGE/APP
    url(r'^s/', include('search.urls')),
    # ACCOUNT PAGE/APP
    url(r'^accounts/', include('account.urls'))
]

website/catalog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models

# There are 3 main classes/*tables*
# The Sex class creates a table with two rows, mens and womens
# The Category class creates a table with rows corresponding to each category in our database
#   Each row has columns that contain it's assigned sex and just the name
# The Product class creates a table with rows corresponding to each product in our database
#   Each row has columns that contain assigned category, name, price, etc...

class Sex(models.Model):
    """model for mens/womens"""
    MENS = 'm'
    WOMENS = 'w'
    # Django has documentation on choice fields, read that
    sex_choices = (
        (MENS, "MENS"),
        (WOMENS, "WOMENS")
    )
    sex_selection = models.CharField(max_length=5, choices=sex_choices, default=MENS)

    def __str__(self):
        return self.get_sex_selection_display()


class Category(models.Model):
    """model for categories"""
    sex = models.ForeignKey(Sex, on_delete=models.CASCADE)
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name + '  ' + str(self.sex)


class Product(models.Model):
    """model for a product"""
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)
    rating = models.FloatField(validators = [MinValueValidator(0), MaxValueValidator(5)], default=0)    # This has not been finished yet, make it so that users can use sessions to enter a product review
    price = models.DecimalField(max_digits=6, decimal_places=2, default=0.00)
    sale_price = models.DecimalField(max_digits=6, decimal_places=2, default=0.00)  # Sale price is 0 by default so when the system detects it's any value between 0 and it's regular price, it displays sale price
    thumbnail_image = models.CharField(max_length=1000, default="/static/catalog/images/Placeholder.jpg")
    description = models.CharField(max_length=1500, default="There is no description available at the moment")
    stockXL = models.IntegerField(default=0)
    stockL = models.IntegerField(default=0)
    stockM = models.IntegerField(default=0)
    stockS = models.IntegerField(default=0)
    featured = models.IntegerField(default=0, validators = [MinValueValidator(0), MaxValueValidator(1)])

    def __str__(self):
        return self.name + ' - ' + self.category.name + ' - ' + str(self.category.sex)


class ProductImage(models.Model):
    """Child model for images going into a product
        This is a many to one relationship using ForeignKey"""
    product = models.ForeignKey(Product, on_delete=models.CASCADE)  # This ForeignKey assigns the object to a parent product object
    image = models.CharField(max_length=200)

    def __str__(self):
        return self.product.name

# manage.py shell
# from (appname).models import Category

website/catalog/views.py
# -*- coding: utf-8 -*-
from django.http import HttpResponse, Http404
from django.shortcuts import render
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from catalog.models import Sex, Category, Product, ProductImage
from django.shortcuts import redirect

# make this block of code a global function so it doesnt need to be repeated everytime
mcata = Sex.objects.get(sex_selection='m').category_set.all()
wcata = Sex.objects.get(sex_selection='w').category_set.all()
cat_context = {'mcata': mcata, 'wcata': wcata}
######################################################################################

def index(request):
    """View request for index page of catalog"""
    MEN = Sex.objects.get(sex_selection='m')
    WOMEN = Sex.objects.get(sex_selection='w')
    featured_list = Product.objects.filter(featured=1)
    context = {'sex': ['m','w'],
               'featured_list': featured_list}
    context.update(cat_context) # this line adds all our category information to the page, it's necessary for our Men's/Women's dropdowns
    return render(request, 'catalog/index.html', context)


def about(request):
    """View request for about us page of catalog"""
    context = cat_context
    return render(request, 'catalog/about_us.html', context)


def mw(request, selection, order='name', order_type='asc'):
    """View request for sex (mens or womens) page of catalog"""
    try:
        selected = Sex.objects.get(sex_selection=selection)
        cata = selected.category_set.all()
        if order_type == 'asc':
            products = Product.objects.order_by(order)
        elif order_type == 'desc':
            products = Product.objects.order_by('-' + order)
        products = products.filter(category__sex__sex_selection=selection)

    except Sex.DoesNotExist:
        raise Http404("Invalid selection")

    if order_type =='asc':
        products = products.order_by(order)
    elif order_type =='desc':
        products = products.order_by('-'+order)

    page = request.GET.get('page', 1) # paginator
    paginator = Paginator(products, 15)
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)

    # Get the index of the current page
    index = products.number - 1  # edited to something easier without index
    # This value is maximum index of your pages, so the last page - 1
    max_index = len(paginator.page_range)
    # You want a range of 7, so lets calculate where to slice the list
    start_index = index - 3 if index >= 3 else 0
    end_index = index + 3 if index <= max_index - 3 else max_index
    # My new page range

    page_range = list(paginator.page_range)
    page_range = page_range[start_index:end_index]

    context = {'selection': selection,
               'selected': selected,
               'cata':cata,
               'page_range': page_range,
               'page': page,
               'products': products,
               'order':order,
               'order_type':order_type,
               }
    context.update(cat_context)
    return render(request, 'catalog/sex.html', context)


def products_list(request, selection, category, order='name', order_type='asc'):
    """View request to display products under a selected category"""
    try:
        selected = Sex.objects.get(sex_selection=selection)
        products = Category.objects.get(sex=selected, name=category).product_set.all()
    except Category.DoesNotExist:
        raise Http404("Category does not exist")

    if order_type =='asc':
        products = products.order_by(order)
    elif order_type =='desc':
        products = products.order_by('-'+order)

    page = request.GET.get('page', 1) # paginator
    paginator = Paginator(products, 15)
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)

    # Get the index of the current page
    index = products.number - 1  # edited to something easier without index
    # This value is maximum index of your pages, so the last page - 1
    max_index = len(paginator.page_range)
    # You want a range of 7, so lets calculate where to slice the list
    start_index = index - 3 if index >= 3 else 0
    end_index = index + 3 if index <= max_index - 3 else max_index
    # My new page range

    page_range = list(paginator.page_range)
    page_range = page_range[start_index:end_index]

    cata = Sex.objects.get(sex_selection=selection).category_set.all()
    context = {'page': page,
               'products': products,
               'page_range':page_range,
               'category': category,
               'selected': selected,
               'cata':cata,
               'order': order,
               'order_type': order_type,
               }
    context.update(cat_context)
    return render(request, 'catalog/products.html', context=context)


def product(request, p_id, thumbnail_image='None'):
    """View request displaying html template for a selected product"""
    try:
        product = Product.objects.get(id=p_id)
        prodImages = ProductImage.objects.filter(product=p_id).select_related()
    except Product.DoesNotExist:
        raise Http404("Product is not in our system")
    if thumbnail_image == 'None':   # Default preview image for the page
        thumbnail_image = product.thumbnail_image
    else:   # Sets a new preview image if our url is provided with one
        thumbnail_image = ProductImage.objects.get(id=thumbnail_image).image

    if product.sale_price > 0 and product.sale_price < product.price: # IF the product is on sale, set it's cart price to the sale price
        cart_price = product.sale_price
    else:   # else, keep regular price
        cart_price = product.price

    if request.method == 'POST':    # check if form is submitted
        if 'add_to_cart' in request.POST:   # if the form was the add to cart form
            cart = request.session.get('cart', {})  # add to item to our cart dictionary
            cart[p_id] = (product.thumbnail_image, product.name, str(cart_price), request.POST.get('size_selection'), request.POST.get('quantity'))
            request.session['cart'] = cart
            return redirect('catalog:cart_confirmation', p_id=p_id) # redirects to page showing confirmation of cart addition

    related_products = Category.objects.get(sex=product.category.sex, name=product.category.name).product_set.all().exclude(id=p_id)
    related_products = related_products[:8]

    context = {'product': product,
                'prodImages': prodImages,
                'p_list':related_products,
                'thumbnail_image':thumbnail_image}
    context.update(cat_context)
    return render(request, 'catalog/product_info.html', context)


def get_cart(request):
    """View function for the user's cart"""
    cart_items = request.session.get('cart', {})
    subtotal = 0
    total = 0
    if request.method == 'POST': # Same formula as add to cart, just opposite
        if 'remove_from_cart' in request.POST:
            cart = request.session.get('cart', {})
            del cart[request.POST.get('p_id')]
            request.session['cart'] = cart

    cart = request.session.get('cart', {})
    for item in cart:
        subtotal += float(cart[item][2])*int(cart[item][4]) # Price*Quantity
    total = round(subtotal*1.13,2)
    tax = total-subtotal

    context = {'cart_items': cart_items,
               'subtotal': subtotal,
               'total': total,
               'tax': tax}
    context.update(cat_context)
    return render(request, 'catalog/cart.html', context)


def cart_confirmation(request, p_id):
    """The page a user sees after adding an item to their cart"""
    try:
        product = Product.objects.get(id=p_id)
    except Product.DoesNotExist:
        raise Http404("Invalid product selection")

    related_products = Category.objects.get(sex=product.category.sex, name=product.category.name).product_set.all().exclude(id=p_id) # get all products will the same category
    related_products = related_products[:9] # split all those items by first 9
    context = {'product': product,
               'p_list':related_products,}
    context.update(cat_context)
    return render(request, 'catalog/cart_confirmation.html', context)

website/catalog/templates/catalog/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>{% block title %}Cliffs{% endblock %}</title>
    <link rel="shortcut icon" href="/static/catalog/images/favicon.png"/>
    {% load staticfiles %}
    <link rel = "stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'catalog/css/style.css' %}"/>
    <script src = "http://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
	<script src = "http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>

<body>
    <!-- Navbar -->
    <nav class="navbar navbar-default">
        <div class="container" style="padding: 10px 15px;">
            <!--header-->
            <div class = "navbar-header">
                <a class="navbar-brand" href="{% url 'catalog:index'%}">
                    <img alt="Brand" src="/static/catalog/images/logo.png" style="width:50px;">
                </a>
                <button type = "button" class = "navbar-toggle" data-toggle= "collapse" data-target="#topNavBar">
                    <span class = 'icon-bar'></span>
                    <span class = 'icon-bar'></span>
                    <span class = 'icon-bar'></span>
                </button>
            </div>

            <!--items-->
            <div class="collapse navbar-collapse" id="topNavBar">
                <ul class="nav navbar-nav">
                    <li class=" dropdown">
                        <a href="{% url 'catalog:mw' selection='m'%}" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">MEN<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'catalog:mw' selection='m' %}">All</a></li>
                            <li role="separator" class="divider"></li>
                            {% for cata in mcata %}
                            <li><a href="{% url 'catalog:products_list' selection='m' category=cata.name %}"> {{cata.name}} </a></li>
                            {% endfor %}
                        </ul>
                    </li>

                    <li class="dropdown">
                        <a href="{% url 'catalog:mw' selection='w'%}" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            WOMEN<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'catalog:mw' selection='w' %}">All</a></li>
                            <li role="separator" class="divider"></li>
                            {% for cata in wcata %}
                            <li><a href="{% url 'catalog:products_list' selection='w' category=cata.name %}">{{ cata.name }} </a></li>
                            {% endfor %}
                        </ul>
                    </li>

                </ul>

                <div class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                        </a>
                        <ul class="dropdown-menu">
                            {% if user.first_name %}
                                <li style="padding-left:20px; padding-bottom:10px;"> Hi, {{user.first_name}}</li>
                            {% endif %}
                            <li><a href="{% url 'account:index' %}" id = "signin"></a></li>
                            {% if user.first_name %}
                                <li role="separator" class="divider"></li>
                                <li><a href="{% url 'account:edit_profile' %}" id = "edit_profile"> Edit Profile</a></li>
                                <li><a href="{% url 'account:logout_view' %}" id = "logout"> Logout </a></li>
                            {% endif %}
                            <script>
                                var user= "{{user}}"

                                if (user === 'AnonymousUser'){
                                    document.getElementById("signin").innerHTML = 'Login';
                                    document.getElementById("signin").href="{% url 'account:index' %}";
                                }
                                else{
                                    document.getElementById("signin").innerHTML = 'Your Account';
                                    document.getElementById("signin").href="{% url 'account:profile' %}";
                                }
                            </script>
                        </ul>
                    </li>
                    <li>
                        <a href="{% url 'catalog:get_cart' %}"><span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span></a>
                    </li>
                </div>

                <form class="navbar-form navbar-right" role="search" action="{% url 'search:search' %}" method="GET" value="{{ request.GET.get }}">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="search..." name="q" >
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="submit" >
                                <span class="glyphicon glyphicon-search" aria-hidden="true" ></span>
                            </button>
                        </span>
                    </div>
                </form>
            </div>
        </div>
    </nav>
    <!-- End of Navbar -->
{% block body %}
{% endblock %}

</body>

<nav class="navbar navbar-default navbar-fixed-bottom">
    <div class="container">
        <ul class="nav navbar-nav">
            <li>
                <a href="{% url 'catalog:about' %}">About us</a>
            </li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
            <li><a href="https://github.com/michaelroudnitski/Threads">
                Github
            </a></li>
        </ul>
    </div>
</nav>

</html>

website/catalog/templates/catalog/cart.html
{% extends 'catalog/base.html'%}
{% block title %}My Cart{% endblock %}

{% block body %}
<div class="container">
    <div class="page-header">
        {% if user.first_name %}
            <h1>{{user.first_name}}'s Cart</h1>
        {% else %}
            <h1>Your Cart | Guest</h1>
        {% endif %}
    </div>
    {% if cart_items %}
    <div class="col-md-8">
        <table class="table">
            <tbody>
                <tr>
                    <td>Item</td>
                    <td>Size</td>
                    <td>Quantity</td>
                    <td>Price</td>
                    <td>Remove</td>
                </tr>
                {% for key, value in cart_items.iteritems %}
                    <tr>
                        <td style="width: 200px;"><a href="{% url 'catalog:prod' p_id=key %}">
                            <img class="img-thumbnail" src={{value.0}} style="width: 132px; height: 132px; object-fit: cover;">
                            <h4>{{ value.1}}</h4>
                        </a></td>
                        <td>
                            <h4>{{ value.3}}</h4>
                        </td>
                        <td>
                            <h4>{{ value.4}}</h4>
                        </td>
                        <td>
                            <h4>{{ value.2}}</h4>
                        </td>
                        <td>
                            <form method="post">
                                {% csrf_token %}
                                <input type="hidden" name="p_id" value={{key}}>
                                <input type="submit" name="remove_from_cart" class="btn btn-danger" value="REMOVE"></td>
                            </form>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="col-md-3">
        <div class="col-md-6">
            <ul style="list-style: none;">
                <li>SUBTOTAL</li>
                <li>HST</li>
                <hr>
                <li><b>TOTAL</b></li>
                <br>
                <li><input type="submit" name="remove_from_cart" class="btn btn-primary" onclick="alert('No.')" value="CHECKOUT"></td></li>
            </ul>
        </div>
        <div class="col-md-6">
            <ul style="list-style: none;">
                <li>$ {{subtotal}}</li>
                <li>$ {{tax}}</li>
                <hr>
                <li><b>$ {{total}}</b></li>
            </ul>
        </div>

    </div>
    {% else %}
        Your shopping cart is empty
    {% endif %}
</div>
{% endblock %}

website/catalog/templates/catalog/cart_confirmation.html
{% extends 'catalog/base.html'%}

{% block body %}
<div class="container" style="max-width:800px;">
    <div class="row">
        <div class="panel panel-success">
            <div class="panel-heading">
                <h3 class="panel-title">{{product.name}} has been added to your cart</h3>
            </div>
            <div class="panel-body">
                <table class="table">
                    <tbody>
                        <tr>
                            <td><a href="{% url 'catalog:prod' p_id=product.id%}"><img src={{product.thumbnail_image}} class="img-thumbnail" style="width: 132px; height: 132px; object-fit: cover;"></a></td>
                            <td><a href="{% url 'catalog:prod' p_id=product.id %}"><h4>{{ product.name }}</h4></a>
                                {% if product.sale_price > 0 and product.sale_price < product.price %}
                                    <h5 class="sale"><span style="color:#333"><strike><h5>$ {{ product.price }}</h5></strike></span> $ {{ product.sale_price }}</h5>
                                {% else %}
                                    <h5>$ {{ product.price }}</h5>
                                {% endif %}</td>
                            <td><a href="{% url 'catalog:get_cart' %}" class="btn btn-success">View Cart</a>
                                <a href="{% url 'catalog:index' %}" class="btn btn-default">Continue Shopping</a></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="page-header">
            <h3 style="text-align:center;">RELATED PRODUCTS</h3>
        </div>
        {% for product in p_list %}
        <div class="col-md-4">
            <a href="{% url 'catalog:prod' p_id=product.id %}">
                    <img class="img-thumbnail" src={{product.thumbnail_image}} style="width: 132px; height: 132px; object-fit: cover; display: block; margin: auto;">
                    <h4 style="text-align:center;">{{ product.name }} </h4></a>
            </a>
            {% if product.sale_price > 0 and product.sale_price < product.price %}
                <p class="sale" style="text-align:center;"><span style="color:#333"><strike>$ {{ product.price }}</strike></span> $ {{ product.sale_price }}</p>
            {% else %}
                <p style="text-align:center;">$ {{ product.price }}</p>
            {% endif %}
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

website/catalog/templates/catalog/index.html
{% extends 'catalog/base.html'%}
her

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-12 tile-img" style="padding: 30px 15px;">
            <a href="{% url 'search:search' %}">
                <img src="/static/catalog/images/banner.png">
            </a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 tile-img">
            <a href="{% url 'catalog:mw' selection='m'%}"><img src="/static/catalog/images/shop_mens.jpg" style='height: 100%; width: 100%; object-fit: contain'></a>
        </div>
        <div class="col-md-6 tile-img">
            <a href="{% url 'catalog:mw' selection='w'%}"><img src="/static/catalog/images/shop_womens.jpg" style='height: 100%; width: 100%; object-fit: contain'></a>
        </div>
    </div>
</div>
<div class="container-fluid" style="background-color:white;">
    <div class="container">
        <div class="row">
            <div class="col-md-12" style="text-align:center;">
                <div class="page-header">
                    <h2>FEATURED</h2>
                </div>
            </div>
            <div class="FeaturedList">
                <ul class="list-inline">
                    {% for product in featured_list %}
                        <li class="inline-item">
                                <div class="thumbnail">
                                    <a href="{% url 'catalog:prod' p_id=product.id %}"><img src={{product.thumbnail_image}}></a>
                                    <div class="caption" style="margin: auto;">
                                        <a href="{% url 'catalog:prod' p_id=product.id %}"><h3 style="text-align: center;">{{ product.name }}</h3></a>
                                        {% if product.sale_price > 0 and product.sale_price < product.price %}
                                        <p class="sale" style="text-align: center;"><span style="color:#333"><strike>$ {{ product.price }}</strike></span> $ {{ product.sale_price }}</p>
                                        {% else %}
                                        <p style="text-align: center;">$ {{ product.price }}</p>
                                        {% endif %}
                                    </div>
                                </div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock %}